import * as t from "io-ts";

export const File = t.exact(t.partial({
  channels: t.array(Definitions.ChannelId),
  comments_count: t.Int,
  created: t.Int,
  display_as_bot: t.boolean,
  editable: t.boolean,
  editor: Definitions.UserId,
  external_id: t.string,
  external_type: t.string,
  external_url: t.string,
  filetype: t.string,
  groups: t.array(Definitions.GroupId),
  has_rich_preview: t.boolean,
  id: Definitions.FileId,
  image_exif_rotation: t.Int,
  ims: t.array(Definitions.DmId),
  is_external: t.boolean,
  is_public: t.boolean,
  is_starred: t.boolean,
  is_tombstoned: t.boolean,
  last_editor: Definitions.UserId,
  mimetype: t.string,
  mode: t.string,
  name: t.string,
  num_stars: t.Int,
  original_h: t.Int,
  original_w: t.Int,
  permalink: t.string,
  permalink_public: t.string,
  pinned_info: Definitions.PinnedInfo,
  pinned_to: t.array(Definitions.Channel),
  pretty_type: t.string,
  preview: t.null,
  public_url_shared: t.boolean,
  reactions: t.array(Objects.Reaction),
  shares: t.exact(t.partial({
    private: t.exact(t.type({

    })),
    public: t.exact(t.type({

    }))
  })),
  size: t.Int,
  source_team: Definitions.Team,
  state: t.string,
  thumb_1024: t.string,
  thumb_1024_h: t.Int,
  thumb_1024_w: t.Int,
  thumb_160: t.string,
  thumb_360: t.string,
  thumb_360_h: t.Int,
  thumb_360_w: t.Int,
  thumb_480: t.string,
  thumb_480_h: t.Int,
  thumb_480_w: t.Int,
  thumb_64: t.string,
  thumb_720: t.string,
  thumb_720_h: t.Int,
  thumb_720_w: t.Int,
  thumb_80: t.string,
  thumb_800: t.string,
  thumb_800_h: t.Int,
  thumb_800_w: t.Int,
  thumb_960: t.string,
  thumb_960_h: t.Int,
  thumb_960_w: t.Int,
  timestamp: t.Int,
  title: t.string,
  updated: t.Int,
  url_private: t.string,
  url_private_download: t.string,
  user: t.string,
  user_team: Definitions.Team,
  username: t.string
}));